# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build Core with Maven
        run: mvn -B install --file pom.xml

      - name: Build Asm with Maven
        run: mvn -B install --file RiscVM-Asm/pom.xml

      - name: Build VM with Maven
        run: mvn -B install --file RiscVM-VM/pom.xml

      - name: Build App with Maven
        run: mvn -B install --file RiscVM-App/pom.xml

      - name: Publish Core to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml --file pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish Asm to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml --file RiscVM-Asm/pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish VM to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml --file RiscVM-VM/pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish App to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml --file RiscVM-App/pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
